apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 5001  # Container port
      nodeport: 32000
  type: LoadBalancer    # Use NodePort if you're not on a cloud provider
