apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 5001  # Container port
      nodePort: 32000   # Port to access on the node (between 30000-32767)
  type: NodePort       # This will expose the service via the node's IP address
